### ISSUE TITLE
Deploy this learning hub as a documentation page

### ISSUE THREAD

**Issue by geoffreylgv** [geoffreylgv/LearningHub#14]
Deploy this learning hub as a documentation page and navigate easily on a web page instead of GitHub READMEs

@bravemaster3 @WassCodeur @fabeklou 
Tell me what do you think ?

**Comment by bravemaster3** [comment]
This is a good idea. It will look more user-friendly for those who visit just for the resources.
Looking forward to seeing the end result.

**Comment by geoffreylgv** [comment]
>[!Note]
Oya @bravemaster3, we are good, it will be deployed in about a minute I'm writing this message.
Really excited 🥳
