### ISSUE TITLE
The docs home page shows 404 for projects

### ISSUE THREAD

**Issue by bravemaster3** [geoffreylgv/LearningHub#23]
When I click on simple shell or printf from here, I get 404 not found.
Did something change?
https://geoffreylgv.github.io/LearningHub/#/

**Comment by geoffreylgv** [comment]
> When I click on simple shell or printf from here, I get 404 not found. Did something change? https://geoffreylgv.github.io/LearningHub/#/

Ok ok thank you @bravemaster3, I will take a look
