### ISSUE TITLE
Order resources by name or add numbering

### ISSUE THREAD

**Issue by abstractHunter** [geoffreylgv/LearningHub#24]
Hello, I think it will be better if the resources and learning materials lists are ordered alphabetically or have a proper numbering if their have an order.
It will make it easy to find a resource if we only know its name (or number).
I can self assign myself i you agree.

**Comment by geoffreylgv** [comment]
> Hello, I think it will be better if the resources and learning materials lists are ordered alphabetically or have a proper numbering if their have an order. It will make it easy to find a resource if we only know its name (or number). I can self assign myself i you agree.

Awesome @milkiyd !, feel free to propose the change, we're glad to have you 🎈

**Comment by abstractHunter** [comment]
👍🏾

**Comment by geoffreylgv** [comment]
Closing this issue 'cause it has been resolved in the pr #25
